### PR TITLE
Homework0

### PR DESCRIPTION
**Pull request by LienShark**
---
A good PR should include the following parts:

- [x] Provide a clear title
- [x] Provide meaningful descriptions in the PR and the commit logs
- [x] Name your branch like ``<github-user-name>-hw#``, e.g., ``myname-hw2-attempt1``
- [x] Merge from your specific branch (***not master***) to the `hw*` branch (***not master***, again)
- [x] Exclude irrelevant files, such as binaries, text files, or dot files
- [x] Make sure tests/CI pass
這是我第二次嘗試，我的步驟如下，希望老師能幫我看一下是否正確，因不常使用所以麻煩老師，不好意思
1.fork老師的repo到我的github上
2.從我的github git clone到電腦
3.從我那邊git clone下來的話沒有hw0分支，所以添加老師的遠端倉庫作為 upstream，把老師的hw0上傳到我的github上
4.在從hw0新增分支LienShark-hw0-attempt1，並在上面完成工作
5.最後上傳到github
6.新增PR
不知道有沒有做錯的想請老師指點

### CODE REVIEW

**Comment by ThreeMonth03** [comment]
> A good PR should include the following parts:
> 
> * [ ]  Provide a clear title
> * [ ]  Provide meaningful descriptions in the PR and the commit logs
> * [ ]  Name your branch like `<github-user-name>-hw#`, e.g., `myname-hw2-attempt1`
> * [ ]  Merge from your specific branch (_**not master**_) to the `hw*` branch (_**not master**_, again)
> * [ ]  Exclude irrelevant files, such as binaries, text files, or dot files
> * [ ]  Make sure tests/CI pass
>   這是我第二次嘗試，我的步驟如下，希望老師能幫我看一下是否正確，因不常使用所以麻煩老師，不好意思
>   1.fork老師的repo到我的github上
>   2.從我的github git clone到電腦
>   3.從我那邊git clone下來的話沒有hw0分支，所以添加老師的遠端倉庫作為 upstream，把老師的hw0上傳到我的github上
>   4.在從hw0新增分支LienShark-hw0-attempt1，並在上面完成工作
>   5.最後上傳到github
>   6.新增PR
>   不知道有沒有做錯的想請老師指點

There is no problem of your steps, but you don't [get the one point](https://github.com/yungyuc/nsdhw_24au/pull/4/checks#step:4:11) in this pr. You may trace the [shell script](https://github.com/yungyuc/nsdhw_24au/blob/master/hw0/validate.sh) and modify the slight blunder. Furthermore, you could write a clear commit message and title to make your pull request better.

**Review by ThreeMonth03 — CHANGES_REQUESTED** [review]
https://github.com/yungyuc/nsdhw_24au/pull/4#issuecomment-2342653535

**Review by ThreeMonth03 — APPROVED** [review]
It looks good to me.

**Comment by LienShark** [comment]
@ThreeMonth03 想請教老師(或助教)，我剛剛改了標題，這是否表示hw0以及上面6項要求我都完成了呢?(因為看沒有打勾，所以留言確認)或是有哪裡要再加強嗎?

**Comment by ThreeMonth03** [comment]
> @ThreeMonth03 想請教老師(或助教)，我剛剛改了標題，這是否表示hw0以及上面6項要求我都完成了呢?(因為看沒有打勾，所以留言確認)或是有哪裡要再加強嗎?

I think the remaining problem is minor, which is not related to the score, so I merge your pr directly. However, if you want to make your pr better, you could try to rebase and squash your commits when writing homework1.

**Pull request merged**
