### PR TITLE
KentLee0820-hw1-attempt2

### PR DESCRIPTION
**Pull request by KentLee0820**
---
A good PR should include the following parts:

- [x] Provide a clear title
- [x] Provide meaningful descriptions in the PR and the commit logs
- [x] Name your branch like ``<github-user-name>-hw#``, e.g., ``myname-hw2-attempt1``
- [x] Merge from your specific branch (***not master***) to the `hw*` branch (***not master***, again)
- [x] Exclude irrelevant files, such as binaries, text files, or dot files
- [x] Make sure tests/CI pass

### CODE REVIEW

**Review by ThreeMonth03 — CHANGES_REQUESTED** [review]
@KentLee0820 Sorry, I mean that the changed files should only include the homework1, could you please try again?

**Comment by ThreeMonth03** [comment]
> @KentLee0820 Sorry, I mean that the changed files should only include the homework1, could you please try again?

You can refer this [pull request](https://github.com/yungyuc/nsdhw_24au/pull/67/files) to commit the right files.

**Comment by KentLee0820** [comment]
> @KentLee0820 Sorry, I mean that the changed files should only include the homework1, could you please try again?
To, TA
I've googled the references about git and watched many videos for days, I still don't understand how to deal with this historical information. 
All my attempts only lead to more chaos information.
I need help ;(

**Comment by ThreeMonth03** [comment]
> > @KentLee0820 Sorry, I mean that the changed files should only include the homework1, could you please try again?
> > To, TA
> > I've googled the references about git and watched many videos for days, I still don't understand how to deal with this historical information.
> > All my attempts only lead to more chaos information.
> > I need help ;(

You should commit your homework1 based on the branch [yungyuc:hw1](https://github.com/yungyuc/nsdhw_24au/tree/hw1), so maybe you should refer the following steps or [this article](https://stackoverflow.com/questions/67699/how-do-i-clone-all-remote-branches):
1. `git clone https://github.com/KentLee0820/nsdhw_24au.git`
2. `git checkout origin/hw1`
3. `git checkout -b KentLee0820-hw1-attempt4`
4. write the homework
5. `git add *`
6. `git commit -m "finish hw1"`
7. `git push origin KentLee0820-hw1-attempt4`
8. make a pr to [yungyuc:hw1](https://github.com/yungyuc/nsdhw_24au/tree/hw1)

**Comment by ThreeMonth03** [comment]
> > > @KentLee0820 Sorry, I mean that the changed files should only include the homework1, could you please try again?
> > > To, TA
> > > I've googled the references about git and watched many videos for days, I still don't understand how to deal with this historical information.
> > > All my attempts only lead to more chaos information.
> > > I need help ;(
> 
> You should commit your homework1 based on the branch [yungyuc:hw1](https://github.com/yungyuc/nsdhw_24au/tree/hw1), so maybe you should refer the following steps or [this article](https://stackoverflow.com/questions/67699/how-do-i-clone-all-remote-branches):
> 
> 1. `git clone https://github.com/KentLee0820/nsdhw_24au.git`
> 2. `git checkout origin/hw1`
> 3. `git checkout -b KentLee0820-hw1-attempt4`
> 4. write the homework
> 5. `git add *`
> 6. `git commit -m "finish hw1"`
> 7. `git push origin KentLee0820-hw1-attempt4`
> 8. make a pr to [yungyuc:hw1](https://github.com/yungyuc/nsdhw_24au/tree/hw1)

By the way, TA will attend [meetup](https://sciwork.dev/meetup/2024/1002-nycu) every Wednesday night, if you have any question about homework, please come to the EC329, and I can help you.

I helped the @YaoKuang making the pr #70 in EC329 few hours ago.

**Pull request closed without merging**
