### PR TITLE
HW1 submitted by lebr0nli

### PR DESCRIPTION
**Pull request by lebr0nli**
This PR is for my HW1.

---
A good PR should include the following parts:

- [x] Provide a clear title
- [x] Provide meaningful descriptions in the PR and the commit logs
- [x] Name your branch like ``<github-user-name>-hw#``, e.g., ``myname-hw2-attempt1``
- [x] Merge from your specific branch (***not master***) to the `hw*` branch (***not master***, again)
- [x] Exclude irrelevant files, such as binaries, text files, or dot files
- [x] Make sure tests/CI pass

### CODE REVIEW

**Review by ThreeMonth03 — APPROVED** [review]
You get 5 points in hw1. I've marked the score on E3. If you have any question, please ask me.

**Comment by lebr0nli** [comment]
> You get 5 points in hw1. I've marked the score on E3. If you have any question, please ask me.

Thanks!
But I have a little question about the validation script:
I'm not very sure about the intended solution, but maybe we could make the validation more lenient, or update the spec if using `exec` is strictly required?

I mean, the spec says: "It should exit with an error code when the specified binary is not found."
But the test case is checking the error message instead of the exit code, which isn't quite consistent with the spec (?)
https://github.com/yungyuc/nsdhw_24au/blob/21090c9f719bdfafa503131fa6f3b786de949459/hw1/validate.sh#L47

With the current validation, some solutions might be blocked even though they meet the spec.
For example, if it checked the exit code instead of the error message as the spec said, I wouldn't need this commit: https://github.com/yungyuc/nsdhw_24au/pull/19/commits/fe4fdfa6990e55ed255f60421766e6ab9e5d4410 :p

**Comment by ThreeMonth03** [comment]
> > You get 5 points in hw1. I've marked the score on E3. If you have any question, please ask me.
> 
> Thanks! But I have a little question about the validation script: I'm not very sure about the intended solution, but maybe we could make the validation more lenient, or update the spec if using `exec` is strictly required?
> 
> I mean, the spec says: "It should exit with an error code when the specified binary is not found." But the test case is checking the error message instead of the exit code, which isn't quite consistent with the spec (?)
> 
> https://github.com/yungyuc/nsdhw_24au/blob/21090c9f719bdfafa503131fa6f3b786de949459/hw1/validate.sh#L47
> 
> With the current validation, some solutions might be blocked even though they meet the spec. For example, if it checked the exit code instead of the error message as the spec said, I wouldn't need this commit: [fe4fdfa](https://github.com/yungyuc/nsdhw_24au/commit/fe4fdfa6990e55ed255f60421766e6ab9e5d4410) :p

It is indeed that it is inconsistence between the spec and the script, and we mark the score based on the validation script. However, according to my personal experience, the validation script will be more and more lenient afterwards.

@yungyuc How do you think?

**Comment by yungyuc** [comment]
> > > You get 5 points in hw1. I've marked the score on E3. If you have any question, please ask me.
> > 
> > 
> > Thanks! But I have a little question about the validation script: I'm not very sure about the intended solution, but maybe we could make the validation more lenient, or update the spec if using `exec` is strictly required?
> > I mean, the spec says: "It should exit with an error code when the specified binary is not found." But the test case is checking the error message instead of the exit code, which isn't quite consistent with the spec (?)
> > https://github.com/yungyuc/nsdhw_24au/blob/21090c9f719bdfafa503131fa6f3b786de949459/hw1/validate.sh#L47
> > 
> > With the current validation, some solutions might be blocked even though they meet the spec. For example, if it checked the exit code instead of the error message as the spec said, I wouldn't need this commit: [fe4fdfa](https://github.com/yungyuc/nsdhw_24au/commit/fe4fdfa6990e55ed255f60421766e6ab9e5d4410) :p
> 
> It is indeed that it is inconsistence between the spec and the script, and we mark the score based on the validation script. However, according to my personal experience, the validation script will be more and more lenient afterwards.
> 
> @yungyuc How do you think?

Please correct me if I am wrong.  The exit code is checked at https://github.com/yungyuc/nsdhw_24au/blob/21090c9f719bdfafa503131fa6f3b786de949459/hw1/validate.sh#L43

The validation script checks the error message so that students would review it.  Keep in mind that this is a practical course.  In reality it is unreasonable to expect all test cases match everything in the problem descriptions.  Problem descriptions ("spec") may or may not exist.  When they exist, they are usually incomplete.  A "clear description" of treatise of nonlinear hyperbolic PDEs may use a couple of books.

Treating the incompleteness is why developers communicate by using test cases.  When the results are not expected, we discuss the test cases just like what we do here.  In this case, the error message is part of "additional spec from the testing code" and should still be required.  Requiring the error message echoes the "Hint: play a trick using bash" in the problem description.

It is absolutely correct to be careful with a spec.  At the same time, be mindful of the priority, which requires discussions like this.  The priority matters more than correct description.

A real defect in the description is the use of the term "error code" instead of the well-defined "exit code".  And the typo for "specified" should certainly be corrected.  PR is welcome.

**Comment by lebr0nli** [comment]
I understand, thank you for your answer, professor and TA! I don't have anymore questions.

> And the typo for "specified" should certainly be corrected. PR is welcome.

Sure, I'll open a PR for the typo :)

**Pull request merged**
