### PR TITLE
HW1 submitted by Bichen07(Attempt4)

### PR DESCRIPTION
**Pull request by Bichen07**
---

implement hw1. By adding countline.sh and countline.py into it. 
cd nsdhw_24au/hw1/Bichen07
../validate.sh
will show result get points

A good PR should include the following parts:

- [x] Provide a clear title
- [x] Provide meaningful descriptions in the PR and the commit logs
- [x] Name your branch like ``<github-user-name>-hw#``, e.g., ``myname-hw2-attempt1``
- [x] Merge from your specific branch (***not master***) to the `hw*` branch (***not master***, again)
- [x] Exclude irrelevant files, such as binaries, text files, or dot files
- [x] Make sure tests/CI pass

### CODE REVIEW

**Review by ThreeMonth03 — COMMENTED** [review]
You only get [1 point](https://github.com/yungyuc/nsdhw_24au/pull/36/checks#step:5:11) in this homework. Do you want to modify your homework?

**Comment by Bichen07** [comment]
Sure! I most need to. I have granted execute permissions already.

**Review by ThreeMonth03 — APPROVED** [review]
Thanks. After the modification, you get 5 points in hw1. Please submit the URL of this pr to new E3.

**Comment by ThreeMonth03** [comment]
> Thanks. After the modification, you get 5 points in hw1. Please submit the URL of this pr to new E3.

I've marked your grade to E3. Feel free to ask me if you have any question.

**Pull request merged**
