### PR TITLE
Sungod3-hw1-attempt2

### PR DESCRIPTION
**Pull request by SUNGOD3**
---
A good PR should include the following parts:

- [x] Provide a clear title
- [x] Provide meaningful descriptions in the PR and the commit logs
- [x] Name your branch like ``<github-user-name>-hw#``, e.g., ``myname-hw2-attempt1``
- [x] Merge from your specific branch (***not master***) to the `hw*` branch (***not master***, again)
- [x] Exclude irrelevant files, such as binaries, text files, or dot files
- [x] Make sure tests/CI pass

### CODE REVIEW

**Review by yungyuc — CHANGES_REQUESTED** [review]
Your PR should not include changesets from others.  You probably did not rebase correctly.

**Comment by SUNGOD3** [comment]
Like [attempt3](https://github.com/yungyuc/nsdhw_24au/pull/66)?

**Comment by yungyuc** [comment]
> Like [attempt3](https://github.com/yungyuc/nsdhw_24au/pull/66)?

That one is good.  It is also ok to rebase on this PR.  Either works as long as the grader is ok with it.

**Comment by ThreeMonth03** [comment]
@SUNGOD3 Thanks, I've graded your score based on pull request #66.

**Pull request closed without merging**
