### PR TITLE
first try for hw3

### PR DESCRIPTION
**Pull request by LienShark**
---
A good PR should include the following parts:

- [ ] Provide a clear title
- [ ] Provide meaningful descriptions in the PR and the commit logs
- [ ] Name your branch like ``<github-user-name>-hw#``, e.g., ``myname-hw2-attempt1``
- [ ] Merge from your specific branch (***not master***) to the `hw*` branch (***not master***, again)
- [ ] Exclude irrelevant files, such as binaries, text files, or dot files
- [ ] Make sure tests/CI pass

### CODE REVIEW

**Review by ThreeMonth03 — CHANGES_REQUESTED** [review]
Please submit the txt file about the operation performance.

**Review by ThreeMonth03 — CHANGES_REQUESTED** [review]
Could you please remove `_matrix.o` and add `performance.txt`?

**Comment by LienShark** [comment]
> Could you please remove `_matrix.o` and add `performance.txt`?

@ThreeMonth03 Yes , I delete it
but I find some problem , I forgot to create a new branch named "LienShark-hw3-attempt1"
I do my homework on branch hw3
do I need to do something for this problem?

**Comment by ThreeMonth03** [comment]
> > Could you please remove `_matrix.o` and add `performance.txt`?
> 
> @ThreeMonth03 Yes , I delete it but I find some problem , I forgot to create a new branch named "LienShark-hw3-attempt1" I do my homework on branch hw3 do I need to do something for this problem?

That's fine.

**Review by ThreeMonth03 — APPROVED** [review]
This pull request looks decent. Could you please submit the pull request link to new E3?

**Comment by LienShark** [comment]
> This pull request looks decent. Could you please submit the pull request link to new E3?

Of course , I just submit it to e3!

**Pull request merged**
