### PR TITLE
HW1 submitted by oscarshiang

### PR DESCRIPTION
**Pull request by OscarShiang**
This PR includes two changes:

1. Reimplement the functionality of countline.py in bash script. The usage is same as the python one.
2. Support changing the python executable used by the script via specifying `PYTHON_BIN` as en environment variable.

---
A good PR should include the following parts:

- [x] Provide a clear title
- [x] Provide meaningful descriptions in the PR and the commit logs
- [x] Name your branch like ``<github-user-name>-hw#``, e.g., ``myname-hw2-attempt1``
- [x] Merge from your specific branch (***not master***) to the `hw*` branch (***not master***, again)
- [x] Exclude irrelevant files, such as binaries, text files, or dot files
- [x] Make sure tests/CI pass

### CODE REVIEW

**Review by ThreeMonth03 — CHANGES_REQUESTED** [review]
It seems that you fail the CI run, please close this pull request and modify your homework.

**Review by ThreeMonth03 — APPROVED** [review]
Thanks, you get 5 points in this homework. Could you please submit the URL of this PR to new E3 in order to mark your grade?

**Comment by OscarShiang** [comment]
Sure. Will submit this link right after.

**Comment by ThreeMonth03** [comment]
I've marked your grade on E3. Feel free to ask me if you have any question.

**Pull request merged**
