### PR TITLE
Add topical list of projects

### PR DESCRIPTION
**Pull request by yungyuc**
I am putting the projects in 3 groups and some sub-groups.  If you want to change the grouping, please file a PR.

I'd also like to know your discord ID on the sciwork server.  If you are OK to leave the information on GitHub, please create a PR to add it in `project/README.rst`, or leave a comment in this PR.  Alternately, you can also paste your project URL in the nsd channel on the server.

* Geometry: @jteng2127, @lebr0nli, @Kang-Ding-Xin-NYCU, @hfkfo, @ntut-xuan, @Bichen07, @yang2829.
* Array and matrix: @ExplorerRay, @SUNGOD3, @LienShark, @OscarShiang, @ian31174117, @leo27945875.
* Other: @Sean20405, @cfmc30, @chris901003, @hsiehbingting.

### CODE REVIEW

**Comment by yungyuc** [comment]
The PR is merged but you can still comment under it.

**Comment by ThreeMonth03** [comment]
I have a quick question. Can students present their project even if their proposals are not accepted?

**Comment by yungyuc** [comment]
> I have a quick question. Can students present their project even if their proposals are not accepted?

In theory a presentation does not require a proposal, but it is very difficult to work out a presentation and get a time slot to present without one. Everything I do for their presentation is based on their proposal, including change of topic.

If someone does not have a proposal merged, their presentation will be unlikely.

**Comment by Sean20405** [comment]
Here is my DC name: sean20405 (The same as GitHub), thanks

**Comment by cfmc30** [comment]
Hi, my Discord ID is cfmc30, thanks.

**Comment by ian31174117** [comment]
Hi, my Discord ID is gootao1961, thanks.

**Comment by c1ydehhx** [comment]
Hi , my Discord ID is Cylinder (xuan910625). Thanks!

**Comment by OscarShiang** [comment]
My Discord ID is `oscarshiang`, thanks.

**Comment by SUNGOD3** [comment]
Hi, my Discord ID is dognus6418, thanks.

**Comment by Bichen07** [comment]
Hi, my Discord ID is bc0757(splay11), thanks.

**Comment by jteng2127** [comment]
Hello, my Discord ID is `jteng2127`, thanks.

**Pull request merged**
