### PR TITLE
complete the hw1

### PR DESCRIPTION
**Pull request by LienShark**
---
A good PR should include the following parts:

- [ ] Provide a clear title
- [ ] Provide meaningful descriptions in the PR and the commit logs
- [ ] Name your branch like ``<github-user-name>-hw#``, e.g., ``myname-hw2-attempt1``
- [ ] Merge from your specific branch (***not master***) to the `hw*` branch (***not master***, again)
- [ ] Exclude irrelevant files, such as binaries, text files, or dot files
- [ ] Make sure tests/CI pass

### CODE REVIEW

**Review by ThreeMonth03 — COMMENTED** [review]
Could you please submit this pr URL to nycu E3?

**Comment by LienShark** [comment]
OK! I will submit this pr URL to nycu E3,and can I check my points in Hw1? thanks!

**Comment by ThreeMonth03** [comment]
> OK! I will submit this pr URL to nycu E3,and can I check my points in Hw1? thanks!

Yes, you get 5 points in this homework. Please check your grade on E3.

**Comment by LienShark** [comment]
Thank you TA

**Pull request merged**
